TOP=../..
include $(TOP)/configure/CONFIG

DB += dbPau.db
DB += dbMux.db
DB += dbPauPattern.db
DB += dbPauBeamcodeTimeslot.db
DB += dbMuxDataSlot.db
DB += dbMuxOffset.db
DB += dbMuxOffset2.db
DB += dbPau.template
DB += dbMux.template
DB += dbMux2.template

include $(TOP)/configure/RULES
